#ifndef _ENGINEERROR_H_
#define _ENGINEERROR_H_

namespace Engine
{
#define PK_NOERROR 0
#define PK_ERROR 1
#define PK_ERROR_NULLPTR 2
#define PK_COMPONENT_NULLPTR 3
#define PK_COMPONENT_CREATE_FAILED 4
#define PK_COMPONENT_EXIST 5
#define PK_COMPONENT_CANNOT_FIND 6
#define PK_LAYER_EXIST 7
#define PK_LAYER_CANNOT_FIND 8
#define PK_GAMEOBJECT_NULLPTR 9
#define PK_GAMEOBJECT_CANNOT_FIND 10
#define PK_INPUT_DEVICE_INIT_FAIL 11
#define PK_MODEL_FILE_NOT_OPENED 12
#define PK_SHADER_CREATE_FAILED 13
#define PK_ERROR_MESHFILE_OPEN 14
#define PK_MESH_CREATE_FAILED 15
#define PK_TEXTURE_CREATE_FAILED 16
#define PK_TRANSFORM_CREATE_FAILED 17
#define PK_CAMERA_CREATE_FAILED 18
#define PK_FMOD_ERROR 19
#define PK_FMOD_DSP_ERROR 20
#define PK_FMOD_SOUND_CREATE_ERROR 21
#define PK_FMOD_CHANNEL_CREATE_ERROR 22
#define PK_FMOD_SOUND_EXIST 23
#define PK_FMOD_CHANNEL_EXIST 24
#define PK_ERROR_IMGUI 25
#define PK_FMOD_DSP_EXIST 26
#define PK_FMOD_CHANNEL_NOT_EXIST 27
#define PK_FMOD_DSP_NOT_EXIST 28
#define PK_LIGHT_CANNOT_FIND 29
#define PK_LIGHT_EXIST 30

	// OpenGL
#define PK_WINDOW_CREATE_ERROR 100
#define PK_GLFW_INIT_FAIL 101
}


#endif //_ENGINEERROR_H_